---
- name: Install PulseAudio
  pacman:
    name: pulseaudio,pulseaudio-alsa,alsa-utils
    state: present

- name: Switch output to newly connected devices
  lineinfile: dest=/etc/pulse/default.pa
              state=present
              line="load-module module-switch-on-connect"
