#!/usr/bin/env bash
set -e

device_name=falco
os_name=${device_name}-arch
luks_mapping=cryptlvm
lvm_vg=$os_name

part_efi_size=512M
part_root_size=64G
part_swap_size=8G

# For installed system. Should be just the basics to troubleshoot and install further.
base_pkgs="git tmux neovim ansible sudo"

# NVMe disks may have a character separating the disk from the partition, while sdX doesn't
disk=/dev/sda
disk_part_sep=

proj_dir=arch-sparker

# 0 for partnum *should* choose the next available partnum and further uses refer to it, but
# it appears buggy and weird (--largest-new seems not to work at least). So be careful with
# your partnums here.
#sgdisk $disk --zap-all --mbrtogpt
#sgdisk $disk --new=1::+$part_efi_size --typecode=1:ef00 --change-name=1:${device_name}-efi
#sgdisk $disk --largest-new=2          --typecode=2:8300 --change-name=2:$os_name

# TODO
#echo "Sleeping for a bit to wait for system to update /dev/disk entries..."
#sleep 2

#mkfs.fat -F 32 /dev/disk/by-partlabel/${device_name}-efi

#cryptsetup luksFormat --type luks2 /dev/disk/by-partlabel/$os_name
#cryptsetup open /dev/disk/by-partlabel/$os_name $luks_mapping

#pvcreate /dev/mapper/$luks_mapping
#vgcreate $lvm_vg /dev/mapper/$luks_mapping
#lvcreate $lvm_vg -n root -L $part_root_size
#lvcreate $lvm_vg -n swap -L $part_swap_size
#lvcreate $lvm_vg -n home -l 100%FREE

#mkfs.ext4 /dev/$lvm_vg/root
mkfs.ext4 /dev/$lvm_vg/home -m 0
mkswap /dev/$lvm_vg/swap

mount /dev/$lvm_vg/root /mnt
mkdir /mnt/boot
mount /dev/disk/by-partlabel/${device_name}-efi /mnt/boot
swapon /dev/$lvm_vg/swap
mkdir /mnt/home
mount /dev/$lvm_vg/home /mnt/home

pacstrap /mnt base $base_pkgs
genfstab -t PARTLABEL /mnt >> /mnt/etc/fstab
echo "HOOKS=(base udev keyboard autodetect filesystems fsck block modconf keymap encrypt lvm2 resume)" >> /mnt/etc/mkinitcpio.conf
cp -r "$(pwd)"/.. /mnt/root/$proj_dir
arch-chroot /mnt /root/$proj_dir/run
arch-chroot /mnt mkinitcpio --allpresets

umount /dev/$lvm_vg/home
umount /dev/disk/by-partlabel/${device_name}-efi
umount /dev/$lvm_vg/root
swapoff /dev/$lvm_vg/swap
vgchange --activate n $lvm_vg
cryptsetup close $luks_mapping
