---
- name: Set timezone
  file:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    state: link

- name: Copy pacman configuration file
  copy: src=pacman.conf dest=/etc/pacman.conf

- name: Refresh pacman package databases
  pacman:
    update_cache: yes

- name: Install inetutils (for Ansible hostname)
  pacman:
    name: inetutils
    state: present

- name: Set the hostname
  hostname: name={{ hostname }}
