---
- name: Install NetworkManager
  pacman:
    name: networkmanager
    state: present

- name: Enable NetworkManager service
  systemd:
    name: NetworkManager
    enabled: yes

- name: Configure NetworkManager
  template:
    src: NetworkManager.conf.j2
    dest: /etc/NetworkManager/NetworkManager.conf

- name: Install chrony (NTPD)
  pacman:
    name: chrony
    state: present

- name: Enable chrony service
  systemd:
    name: chronyd
    enabled: yes
