---
- name: Copy pacman configuration file
  copy: src=pacman.conf dest=/etc/pacman.conf

- name: Refresh pacman package databases
  pacman:
    update_cache: yes
  changed_when: false
  tags:
  - TODO

- name: Install base system packages
  pacman:
    name: "{{ packages.base }}"
    state: present
  tags:
    - packages

- name: Create pacman hook directory
  file: path=/etc/pacman.d/hooks
        state=directory
  tags:
    - packages

- name: Push pacman cache cleanup service
  copy: src=paccache.service dest=/etc/systemd/system/paccache.service
  notify:
    - reload systemd config
  tags:
    - packages

- name: Push pacman cache cleanup timer
  copy: src=paccache.timer dest=/etc/systemd/system/paccache.timer
  notify:
    - reload systemd config
    - restart paccache
  tags:
    - packages

- name: Enable and start pacman cache cleanup timer
  service: name=paccache.timer enabled=yes state=started
  tags:
    - packages
