---
- name: Create user group
  group:
    name: "{{ user.name }}"
    gid: "{{ user.uid }}"
    state: present
  tags:
  - user

- name: Create user
  user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    uid: "{{ user.uid }}"
    shell: "{{ user.shell }}"
    # TODO: remove when known safe
    #password: ""
    #update_password: on_create
  tags:
  - user

- name: Create user home directories
  file:
    path: /home/{{ user.name }}/{{ item }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  with_items:
  - data
  - bin
  - tmp
  tags:
  - user
